force-app/main/default/objects/P2C_EnhancedListviewAction__c/P2C_EnhancedListviewAction__c.object-meta.xml
<CustomObject>
    <label>Enhanced Listview Action</label>
    <nameField>
        <label>P2C_EnhancedListviewAction Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Enhanced Listview actions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/P2C_EnhancedListviewAction__c/fields/ActionType__c.field-meta.xml
<CustomField>
    <fullName>ActionType__c</fullName>
    <label>Action type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>URL</fullName>
            </value>
            <value>
                <fullName>Flow</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/P2C_EnhancedListviewAction__c/fields/EnhancedListviewConfig__c.field-meta.xml
<CustomField>
    <fullName>EnhancedListviewConfig__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Enhanced Listview Config</label>
    <referenceTo>P2C_EnhancedListviewConfig__c</referenceTo>
    <relationshipLabel>Enhanced Listview actions</relationshipLabel>
    <relationshipName>Enhanced_Listview_actions</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/P2C_EnhancedListviewAction__c/fields/FlowApiName__c.field-meta.xml
<CustomField>
    <fullName>FlowApiName__c</fullName>
    <label>Flow Api Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/P2C_EnhancedListviewAction__c/fields/ShowActionWhen__c.field-meta.xml
<CustomField>
    <fullName>ShowActionWhen__c</fullName>
    <label>Show action when</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Always</fullName>
                <default>true</default>
                <label>Always</label>
            </value>
            <value>
                <fullName>One record is selected</fullName>
            </value>
            <value>
                <fullName>One or more records are selected</fullName>
            </value>
            <value>
                <fullName>More than one record is selected</fullName>
            </value>
            <value>
                <fullName>Admins Only</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/P2C_EnhancedListviewConfig__c/P2C_EnhancedListviewConfig__c.object-meta.xml
<CustomObject>
    <label>Enhanced Listview Config</label>
    <nameField>
        <label>P2C_EnhancedListviewConfig Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Enhanced Listview configs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/P2C_EnhancedListviewConfig__c/fields/ObjectApiName__c.field-meta.xml
<CustomField>
    <fullName>ObjectApiName__c</fullName>
    <label>ObjectApiName</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/P2C_EnhancedListviewConfig__c/fields/SharedListview__c.field-meta.xml
<CustomField>
    <fullName>SharedListview__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Defines if the listview can be used by other users.
Default to true</description>
    <label>Shared Listview</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/P2C_EnhancedListviewDefaultField__c/P2C_EnhancedListviewDefaultField__c.object-meta.xml
<CustomObject>
    <label>Enhanced Listview Default Field</label>
    <nameField>
        <label>P2C_EnhancedListviewDefaultField Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Enhanced Listview default fields</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/P2C_EnhancedListviewDefaultField__c/fields/DisplayOrder__c.field-meta.xml
<CustomField>
    <fullName>DisplayOrder__c</fullName>
    <label>Display order</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/P2C_EnhancedListviewDefaultField__c/fields/EnhancedListviewConfig__c.field-meta.xml
<CustomField>
    <fullName>EnhancedListviewConfig__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Enhanced Listview Config</label>
    <referenceTo>P2C_EnhancedListviewConfig__c</referenceTo>
    <relationshipName>Enhanced_Listview_default_fields</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/P2C_EnhancedListviewDefaultField__c/fields/FieldAPIName__c.field-meta.xml
<CustomField>
    <fullName>FieldAPIName__c</fullName>
    <label>Field API Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/P2C_EnhancedListviewDefaultField__c/fields/IsEditable__c.field-meta.xml
<CustomField>
    <fullName>IsEditable__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Editable</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/P2C_EnhancedListviewDefaultField__c/fields/IsLinkToRecord__c.field-meta.xml
<CustomField>
    <fullName>IsLinkToRecord__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is link to record</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/P2C_EnhancedListviewDefaultField__c/fields/LinkHoverDetailsLayout__c.field-meta.xml
<CustomField>
    <fullName>LinkHoverDetailsLayout__c</fullName>
    <description>JSON representation of the layout to use in details popup when the hover option is activated</description>
    <label>Link Hover Details Layout</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/P2C_EnhancedListviewDefaultField__c/fields/LinkHoverShowDetails__c.field-meta.xml
<CustomField>
    <fullName>LinkHoverShowDetails__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Link Hover Show Details</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/P2C_EnhancedListviewDefaultField__c/fields/LookupFieldToDisplay__c.field-meta.xml
<CustomField>
    <fullName>LookupFieldToDisplay__c</fullName>
    <description>Api name of the field on the lookup target object to show in the table</description>
    <label>Lookup Field to display</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/P2C_EnhancedListviewDefaultField__c/fields/PopupAlignment__c.field-meta.xml
<CustomField>
    <fullName>PopupAlignment__c</fullName>
    <label>Popup alignment</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Auto</fullName>
            </value>
            <value>
                <fullName>Left</fullName>
            </value>
            <value>
                <fullName>Right</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/P2C_EnhancedListviewDefaultField__c/fields/PopupWidth__c.field-meta.xml
<CustomField>
    <fullName>PopupWidth__c</fullName>
    <label>Popup width (pixels)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/P2C_EnhancedListviewDefaultField__c/fields/TableColumnLabel__c.field-meta.xml
<CustomField>
    <fullName>TableColumnLabel__c</fullName>
    <label>Table column label</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/P2C_EnhancedListviewFilter__c/P2C_EnhancedListviewFilter__c.object-meta.xml
<CustomObject>
    <label>Enhanced Listview Filter</label>
    <nameField>
        <label>P2C_EnhancedListViewFilter Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Enhanced Listview Filters</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/P2C_EnhancedListviewFilter__c/fields/Condition__c.field-meta.xml
<CustomField>
    <fullName>Condition__c</fullName>
    <label>Condition</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>= {value}</fullName>
                <label>equals</label>
            </value>
            <value>
                <fullName>&lt;&gt; {value}</fullName>
                <label>not equals</label>
            </value>
            <value>
                <fullName>like &apos;%{value}%&apos;</fullName>
                <label>contains</label>
            </value>
            <value>
                <fullName>like &apos;{value}%&apos;</fullName>
                <label>starts with</label>
            </value>
            <value>
                <fullName>like &apos;%{value}&apos;</fullName>
                <label>ends with</label>
            </value>
            <value>
                <fullName>in ({value})</fullName>
                <label>in</label>
            </value>
            <value>
                <fullName>&gt; {value}</fullName>
                <label>Greater than</label>
            </value>
            <value>
                <fullName>&lt; {value}</fullName>
                <label>Less than</label>
            </value>
            <value>
                <fullName>(not {field} like &apos;%{value}%&apos;)</fullName>
                <label>Not contains</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/P2C_EnhancedListviewFilter__c/fields/EnhancedListviewConfig__c.field-meta.xml
<CustomField>
    <fullName>EnhancedListviewConfig__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Enhanced Listview Config</label>
    <referenceTo>P2C_EnhancedListviewConfig__c</referenceTo>
    <relationshipLabel>Enhanced Listview Filters</relationshipLabel>
    <relationshipName>Enhanced_Listview_Filters</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/P2C_EnhancedListviewSortingField__c/P2C_EnhancedListviewSortingField__c.object-meta.xml
<CustomObject>
    <label>Enhanced Listview Sorting Field</label>
    <nameField>
        <label>P2C_EnhancedListviewSortingField Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Enhanced Listview sorting fields</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/P2C_EnhancedListviewSortingField__c/fields/EnhancedListviewConfig__c.field-meta.xml
<CustomField>
    <fullName>EnhancedListviewConfig__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Enhanced Listview Config</label>
    <referenceTo>P2C_EnhancedListviewConfig__c</referenceTo>
    <relationshipLabel>Enhanced Listview sorting fields</relationshipLabel>
    <relationshipName>Enhanced_Listview_sorting_fields</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/P2C_EnhancedListviewSortingField__c/fields/SortingDirection__c.field-meta.xml
<CustomField>
    <fullName>SortingDirection__c</fullName>
    <label>Sorting direction</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>ASC</fullName>
                <default>true</default>
                <label>ASC</label>
            </value>
            <value>
                <fullName>DESC</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/P2C_EnhancedListviewSortingField__c/fields/SortingOrder__c.field-meta.xml
<CustomField>
    <fullName>SortingOrder__c</fullName>
    <label>Sorting order</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/P2C_EnhancedListviewUserPreferences__c/P2C_EnhancedListviewUserPreferences__c.object-meta.xml
<CustomObject>
    <label>Enhanced Listview User preferences</label>
    <nameField>
        <label>Enhanced Listview User preferences Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Enhanced Listview User preferences</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/P2C_EnhancedListviewUserPreferences__c/fields/EnhancedListviewConfig__c.field-meta.xml
<CustomField>
    <fullName>EnhancedListviewConfig__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Enhanced Listview Config</label>
    <referenceTo>P2C_EnhancedListviewConfig__c</referenceTo>
    <relationshipLabel>Enhanced Listview User preferences</relationshipLabel>
    <relationshipName>EnhancedListviewUserPreferences</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/P2C_EnhancedListView_Test.cls
@isTest
public with sharing class P2C_EnhancedListView_Test {

    @TestSetup
    static void setupTests(){
        User usr = [SELECT Id, ALS_Bypass_Validation_rule__c FROM User WHERE Id = :UserInfo.getUserId()];
        usr.ALS_Bypass_Validation_rule__c = true;
        update usr;
        
        P2C_EnhancedListviewConfig__c cfg = new P2C_EnhancedListviewConfig__c();
        cfg.ObjectApiName__c = 'Opportunity';
        cfg.Name = 'test';
        cfg.SharedListview__c = true;
        insert cfg;

        P2C_EnhancedListviewDefaultField__c fld1 = new P2C_EnhancedListviewDefaultField__c();
        fld1.Name = 'name';
        fld1.EnhancedListviewConfig__c = cfg.Id;
        fld1.FieldAPIName__c = 'Name';
        fld1.TableColumnLabel__c = 'Name';
        fld1.DisplayOrder__c = 1;
        fld1.IsEditable__c = true;
        fld1.IsLinkToRecord__c = true;
        fld1.LinkHoverShowDetails__c = true;
        fld1.LinkHoverDetailsLayout__c = '{"columns":[{"label": "firstcol","rows":[{"fieldApiName": "OwnerId"},{"fieldApiName": "TYPE_D_OPPORTUNITE__c"},{"fieldApiName": "Equipement_en_place__c"}]},{"label": "secondcol","rows":[{"fieldApiName": "Numero_de_devis_SF__c"},{"fieldApiName": "Commentaire_interne__c"},{"fieldApiName": "Commentaire_Demande_de_Devis__c"}]}]}';
        fld1.LookupFieldToDisplay__c = 'Name';
        fld1.PopupWidth__c = 500;
        fld1.PopupAlignment__c = 'Auto';
        
        P2C_EnhancedListviewDefaultField__c fld2 = new P2C_EnhancedListviewDefaultField__c();
        fld2.Name = 'owner';
        fld2.EnhancedListviewConfig__c = cfg.Id;
        fld2.FieldAPIName__c = 'OwnerId';
        fld2.TableColumnLabel__c = 'Propriétaire';
        fld2.DisplayOrder__c = 2;
        fld2.IsEditable__c = true;
        fld2.IsLinkToRecord__c = true;
        fld2.LookupFieldToDisplay__c = 'Name';
        insert new List<P2C_EnhancedListviewDefaultField__c> {fld1, fld2};

        P2C_EnhancedListviewFilter__c filt = new P2C_EnhancedListviewFilter__c();
        filt.EnhancedListviewConfig__c = cfg.Id;
        filt.FieldAPIName__c = 'Name';
        filt.Condition__c = 'like \'%{value}%\'';
        filt.Value__c = 'test';
        insert filt;

        P2C_EnhancedListviewSortingField__c sortfld = new P2C_EnhancedListviewSortingField__c();
        sortfld.EnhancedListviewConfig__c = cfg.Id;
        sortfld.FieldAPIName__c = 'Name';
        sortfld.SortingDirection__c = 'DESC';
        sortfld.SortingOrder__c = 1;
        insert sortfld;

        P2C_EnhancedListviewAction__c action = new P2C_EnhancedListviewAction__c();
        action.EnhancedListviewConfig__c = cfg.Id;
        action.Label__c = 'testaction';
        action.FlowApiName__c = 'testflow';
        action.ActionType__c = 'Flow';
        action.ShowActionWhen__c = 'One record is selected';
        insert action;


        TestDataFactory.createOpportunity();
    }

    @isTest
    public static void testGetListviewConfig() {
        String result = P2C_EnhancedListView.getListviewConfig('test');

        Assert.isNotNull(result);
    }

    @isTest
    public static void testListviewDescribeConditionToEnhancedListviewCondition() {
        Assert.areEqual('= {value}', P2C_EnhancedListView.ListviewDescribeConditionToEnhancedListviewCondition('equals'));
        Assert.areEqual('<> {value}', P2C_EnhancedListView.ListviewDescribeConditionToEnhancedListviewCondition('notEquals'));
        Assert.areEqual('< {value}', P2C_EnhancedListView.ListviewDescribeConditionToEnhancedListviewCondition('lessThan'));
        Assert.areEqual('> {value}', P2C_EnhancedListView.ListviewDescribeConditionToEnhancedListviewCondition('greaterThan'));
        Assert.areEqual('<= {value}', P2C_EnhancedListView.ListviewDescribeConditionToEnhancedListviewCondition('lessThanOrEqualTo'));
        Assert.areEqual('>= {value}', P2C_EnhancedListView.ListviewDescribeConditionToEnhancedListviewCondition('greaterThanOrEqualTo'));
        Assert.areEqual('(not {field} like {value})', P2C_EnhancedListView.ListviewDescribeConditionToEnhancedListviewCondition('notLike'));
        Assert.areEqual('like {value}', P2C_EnhancedListView.ListviewDescribeConditionToEnhancedListviewCondition('like'));
        Assert.areEqual('like {value}', P2C_EnhancedListView.ListviewDescribeConditionToEnhancedListviewCondition('includes'));
        Assert.areEqual('(not {field} like {value})', P2C_EnhancedListView.ListviewDescribeConditionToEnhancedListviewCondition('excludes'));
        Assert.areEqual('in ({value})', P2C_EnhancedListView.ListviewDescribeConditionToEnhancedListviewCondition('in'));
        Assert.areEqual('= ({value})', P2C_EnhancedListView.ListviewDescribeConditionToEnhancedListviewCondition('notIn'));
    }

    @isTest
    public static void testExecuteQueryCount() {
        String result = P2C_EnhancedListView.executeQueryCount('Opportunity', null, ' USING SCOPE everything ');

        Assert.isNotNull(result);
        Assert.areEqual(1, Integer.valueOf(result));
    }

    @isTest
    public static void testExecuteQuery() {
        String result = P2C_EnhancedListView.executeQuery('Opportunity', 'Id, Name', ' USING SCOPE everything ', null, null, 200, 0);

        Assert.isNotNull(result);
    }

    @isTest
    public static void testGetObjectFieldsNamesSorted() {
        String result = P2C_EnhancedListView.getObjectFieldsNamesSorted('Opportunity');

        Assert.isNotNull(result);
        Assert.isTrue(result.containsIgnoreCase('StageName'));
    }

    @isTest
    public static void testGetObjectInfoFromApiName() {
        String result = P2C_EnhancedListView.getObjectInfoFromApiName('Opportunity');

        Assert.isNotNull(result);
        P2C_OptionValueLabel option = (P2C_OptionValueLabel)JSON.deserialize(result, P2C_OptionValueLabel.class);
        Assert.isTrue(option.value == 'Opportunity');
    }

    @isTest
    public static void testGetListview() {
        P2C_EnhancedListviewConfig__c cfg = [SELECT Id, Name FROM P2C_EnhancedListviewConfig__c LIMIT 1];

        Test.startTest();

        Test.setMock(HttpCalloutMock.class, new P2C_MockHttpServiceData());
        String result = P2C_EnhancedListView.getListview('Opportunity', cfg.Id);
        
        Test.stopTest();

        Assert.isNotNull(result);
    }

    @isTest
    public static void testPinListview() {
        P2C_EnhancedListviewConfig__c cfg = [SELECT Id, Name FROM P2C_EnhancedListviewConfig__c LIMIT 1];
        ListView lv = [SELECT Id, Name, DeveloperName, NamespacePrefix, SobjectType FROM ListView WHERE SobjectType = 'Opportunity' LIMIT 1];

        Test.startTest();

        P2C_EnhancedListView.pinUnpinListview(lv.Id, cfg.Id);
        P2C_EnhancedListView.pinUnpinListview(cfg.Id, cfg.Id);

        Test.stopTest();

        List<P2C_EnhancedListviewUserPreferences__c> prefs = [SELECT Id, Name FROM P2C_EnhancedListviewUserPreferences__c];
        Assert.isNotNull(prefs);
        Assert.isTrue(!prefs.isEmpty());
    }
}